# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5a63eca2df5723d0c1247d228af5f9d3c960e7c902b2acbf660c81d78e465f507deabe61f3f17aca5d4269bed33b0b66c3b052430430d2354b14fc1c28798008

test:
  secret_key_base: 0379e45a7d520f7cc8fff6315b5acef48d28449e6e20d6fecf90ee2cfdbd1286ec081d328699bbef00650f2d3aceb19941783d270a7d432941c5473159d4afe2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
